### ISSUE TITLE
您好，我根据您提供的脚本生成了自己的数据集，但在运行的时候，他报了以下错误。

### ISSUE THREAD

**Issue by zbzzz** [DVLP-CMATERJU/RectiNet#11]
您好，我根据您提供的脚本生成了自己的数据集，但在运行的时候，他报了以下错误。
      raise KeyError("%s is not a file in the archive"% key)
keyError:''grid is  not a file in the archive'
是我数据集格式存在问题吗，希望您能指点一下

**Comment by hmrishavbandy** [comment]
Please provide the complete error log (the file which is causing the error down to the line number).

**Comment by zbzzz** [comment]
Thank you very much for your reply and your contribution in the field.
The following is the error message:


Traceback (most recent call last):
  File "train.py", line 253, in <module>
    train(model, int(parser.batch_size), first,int(parser.epochs), dataset_train,dataset_test, optimizer, parser.save_path,parser.log,parser.testing)
  File "train.py", line 127, in train
    for inputs, edges,grid in train_loader:
  File "/home/admin1/anaconda3/envs/pyto37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/home/admin1/anaconda3/envs/pyto37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "/home/admin1/anaconda3/envs/pyto37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "/home/admin1/anaconda3/envs/pyto37/lib/python3.7/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/admin1/anaconda3/envs/pyto37/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/admin1/anaconda3/envs/pyto37/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/admin1/anaconda3/envs/pyto37/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/admin1/wendang/RectiNet-master/loader/dataset.py", line 61, in __getitem__
    print('lalalalalalalal',label['grid'])
  File "/home/admin1/anaconda3/envs/pyto37/lib/python3.7/site-packages/numpy/lib/npyio.py", line 262, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
KeyError: 'grid is not a file in the archive'




I think there is a problem with my npz script. I made the following changes from line 466 of the original script:

  if save_docimage:
                # cv2.imwrite(save_dir + '/{}_{}_ori.jpg'.format(i, i_cycle), image_save[0])
                cv2.imwrite(save_dir + '/{}_{}_disorted.jpg'.format(i, i_cycle), image_disorted_save[0])
                # cv2.imwrite(save_dir + '/{}_{}_cycle.jpg'.format(i, i_cycle), image_cycle_save[0])
            output_datasets.append({
                'img_ori': image_save[0],
                'img': image_disorted_save[0],
                'grid_back': grid_S_save
            })

            # save_name =list2[0]+'.npz'
            save_name = data_save+'/{}_{}_disorted.npz'.format(i, i_cycle)
            # print('...........',save_name)
            # # img_idx += 1
            # with open(save_name, 'wb') as f_out:
            #     # pickle.dump(output_datasets, f_out)
            #     print(f_out)
            #     np.savez(f_out, vol =output_datasets)
            np.savez(save_name, img_ori=image_save[0],img=image_disorted_save[0],grid_back=grid_S_save)
            print('save train data to: ', save_name)

**Comment by hmrishavbandy** [comment]
Change `grid_back` to `grid` in the dictionary that you save as npz

**Comment by zbzzz** [comment]
Thank you for your reply.
This is the changed script：          
 np.savez(save_name, img_ori=image_save[0],img=image_disorted_save[0],grid=grid_S_save)

Now there are new problems:

Traceback (most recent call last):
  File "train.py", line 253, in <module>
    train(model, int(parser.batch_size), first,int(parser.epochs), dataset_train,dataset_test, optimizer, parser.save_path,parser.log,parser.testing)
  File "train.py", line 127, in train
    for inputs, edges,grid in train_loader:
  File "/home/admin1/anaconda3/envs/pyto37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/home/admin1/anaconda3/envs/pyto37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "/home/admin1/anaconda3/envs/pyto37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "/home/admin1/anaconda3/envs/pyto37/lib/python3.7/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/admin1/anaconda3/envs/pyto37/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/admin1/anaconda3/envs/pyto37/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/admin1/anaconda3/envs/pyto37/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/admin1/wendang/RectiNet-master/loader/dataset.py", line 74, in __getitem__
    edges=self.transform(edges)
  File "/home/admin1/anaconda3/envs/pyto37/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 49, in __call__
    img = t(img)
  File "/home/admin1/anaconda3/envs/pyto37/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 76, in __call__
    return F.to_tensor(pic)
  File "/home/admin1/anaconda3/envs/pyto37/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 48, in to_tensor
    img = torch.from_numpy(pic.transpose((2, 0, 1)))
ValueError: axes don't match array

**Comment by hmrishavbandy** [comment]
Ditch the `transforms` conversion when converting edgemaps and try to convert to tensor with `torch.tensor(xx)`

**Comment by zbzzz** [comment]
I'm sorry I didn't fully understand your meaning

What you mean is to change the code after line 72 in dataset.py ：
   
          if self.transform:
			img = self.transform(img)
			edges=self.transform(edges)
Change to：
                       edges=torch.tensor(edges)  ？

If this is changed, it will be like this:

Traceback (most recent call last):
  File "train.py", line 253, in <module>
    train(model, int(parser.batch_size), first,int(parser.epochs), dataset_train,dataset_test, optimizer, parser.save_path,parser.log,parser.testing)
  File "train.py", line 134, in train
    loss_grid=nn.MSELoss()(out1,grid)
  File "/home/admin1/anaconda3/envs/pyto37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/admin1/anaconda3/envs/pyto37/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 530, in forward
    return F.mse_loss(input, target, reduction=self.reduction)
  File "/home/admin1/anaconda3/envs/pyto37/lib/python3.7/site-packages/torch/nn/functional.py", line 3279, in mse_loss
    expanded_input, expanded_target = torch.broadcast_tensors(input, target)
  File "/home/admin1/anaconda3/envs/pyto37/lib/python3.7/site-packages/torch/functional.py", line 73, in broadcast_tensors
    return _VF.broadcast_tensors(tensors)  # type: ignore[attr-defined]
RuntimeError: The size of tensor a (256) must match the size of tensor b (512) at non-singleton dimension 2

**Comment by hmrishavbandy** [comment]
You are using different image/edgemap dimensions. Fix the generated image dimensions and align them to the model output dimension.

**Comment by zbzzz** [comment]
After the dataset and model are adjusted to 512 pixels, the batch size is set to 2, and the following error occurs：

Traceback (most recent call last):
  File "train.py", line 258, in <module>
    train(model, int(parser.batch_size), first,int(parser.epochs), dataset_train,dataset_test, optimizer, parser.save_path,parser.log,parser.testing)
  File "train.py", line 141, in train
    loss_output=loss_grid+(lamda*(nn.BCELoss()(out2.float(),edges.float())))
  File "/home/admin1/anaconda3/envs/pyto37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/admin1/anaconda3/envs/pyto37/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 613, in forward
    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
  File "/home/admin1/anaconda3/envs/pyto37/lib/python3.7/site-packages/torch/nn/functional.py", line 3076, in binary_cross_entropy
    "Please ensure they have the same size.".format(target.size(), input.size())
ValueError: Using a target size (torch.Size([2, 512, 512])) that is different to the input size (torch.Size([2, 1, 512, 512])) is deprecated. Please ensure they have the same size.

**Comment by hmrishavbandy** [comment]
It's just saying that the input size has one extra channel. Either do `input.squeeze()` or `target.unsqueeze(1)`

**Comment by zbzzz** [comment]
Thank you very much for your help. Now the model can be trained.
but the predicte image effect is very bad. 
![2022-11-05 15-04-25屏幕截图](https://user-images.githubusercontent.com/51048073/200107568-7c081b46-ff45-4d67-afcb-6df2c0090ff6.png)
![2022-11-05 15-06-50屏幕截图](https://user-images.githubusercontent.com/51048073/200107558-8d19fe1b-d539-46e8-a385-4bf321a1a6a7.png)


There are only 60 training data sets. The reason for poor effect is that there are few datasets or the dimensions are incorrect. The following are the changes to the dimension:
![2022-11-05 15-07-52屏幕截图](https://user-images.githubusercontent.com/51048073/200107775-3eda5216-cdcb-4649-9c42-7e94fced34fb.png)

**Comment by hmrishavbandy** [comment]
1. Train with more data, both in quantity and diversity
2. Train with 256 size images if possible

**Comment by Testhjf** [comment]
> Thank you very much for your help. Now the model can be trained. but the predicte image effect is very bad. ![2022-11-05 15-04-25屏幕截图](https://user-images.githubusercontent.com/51048073/200107568-7c081b46-ff45-4d67-afcb-6df2c0090ff6.png) ![2022-11-05 15-06-50屏幕截图](https://user-images.githubusercontent.com/51048073/200107558-8d19fe1b-d539-46e8-a385-4bf321a1a6a7.png)
> 
> There are only 60 training data sets. The reason for poor effect is that there are few datasets or the dimensions are incorrect. The following are the changes to the dimension: ![2022-11-05 15-07-52屏幕截图](https://user-images.githubusercontent.com/51048073/200107775-3eda5216-cdcb-4649-9c42-7e94fced34fb.png)

哥，后来你训练成功了吗 ，效果咋样
